# Generated by Django 4.1.4 on 2022-12-10 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_categorydb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admindb',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='admin'),
        ),
    ]
