# Generated by Django 4.1.4 on 2022-12-30 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='registration',
            new_name='registrationdb',
        ),
    ]
