# Generated by Django 4.1.4 on 2023-01-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0004_savecontactdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savecontactdb',
            name='Message',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
